[variables]
    NIXPACKS_PHP_VERSION = '8.2'

[phases.setup]
    nixPkgs = ['...', 'php82', 'php82Packages.composer']

[phases.install]
    cmds = ['composer install --optimize-autoloader --no-interaction --no-scripts']
