databases:
  - name: marketing-db
    databaseName: marketing
    plan: free
    region: frankfurt

services:
  - type: web
    name: smartnexus-marketing
    plan: free
    runtime: php
    region: frankfurt
    repo: https://github.com/omarch446/PI_DEV_AssistanceIntelligente
    branch: Marketing
    buildCommand: composer install --no-dev --optimize-autoloader && php bin/console cache:clear --env=prod
    startCommand: heroku-php-apache2 public/
    envVars:
      - key: APP_ENV
        value: prod
      - key: APP_DEBUG
        value: "0"
      - key: APP_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: marketing-db
          property: connectionString
